import CoverMovieTemplate from '../images/template-movie.png';

export const movies = [
  {
    id: 1,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 2,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 3,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 4,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 5,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 6,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 7,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 8,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 9,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 10,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 11,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 12,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 13,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 14,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 15,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 16,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 17,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 18,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 19,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 20,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
]

export const saveMovies = [
  {
    id: 1,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 2,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 3,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 4,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 5,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
  {
    id: 6,
    name: '33 слова о дизайне',
    image: CoverMovieTemplate,
    trailerLink: "https://www.youtube.com/watch?v=5ovzC93EneA",
  },
]
