const SIZE_WIDTH_LARGE = 1280;
const SIZE_WIDTH_MEDIUM = 1024;
const SIZE_WIDTH_SMALL = 650;

const NUMBER_MOVIES_TO_RENDER_MAX = 16;
const NUMBER_MOVIES_TO_RENDER_LARGE = 12;
const NUMBER_MOVIES_TO_RENDER_MEDIUM = 8;
const NUMBER_MOVIES_TO_RENDER_SMALL = 5;

const NUMBER_MOVIES_TO_ADD_MAX = 4;
const NUMBER_MOVIES_TO_ADD_MEDIUM = 3;
const NUMBER_MOVIES_TO_ADD_SMALL = 2;

export {
  SIZE_WIDTH_LARGE,
  SIZE_WIDTH_MEDIUM,
  SIZE_WIDTH_SMALL,

  NUMBER_MOVIES_TO_RENDER_MAX,
  NUMBER_MOVIES_TO_RENDER_LARGE,
  NUMBER_MOVIES_TO_RENDER_MEDIUM,
  NUMBER_MOVIES_TO_RENDER_SMALL,

  NUMBER_MOVIES_TO_ADD_MAX,
  NUMBER_MOVIES_TO_ADD_MEDIUM,
  NUMBER_MOVIES_TO_ADD_SMALL
}
